name: potato_notes
description: Official POSP notes app
publish_to: 'none'
version: 2.0.0-beta1+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqlite3_flutter_libs:
  moor:
  json_serializable:
  sqflite:
  path_provider:
  flutter_staggered_grid_view:
  photo_view:
  image_picker:
  back_button_interceptor:
  shared_preferences: ^0.5.12+4
  local_auth:
  flutter_secure_storage:
  http: 
  jwt_decode:
  intl:
  flutter_local_notifications:
  share_plus: ^1.2.0
  animations:
  material_design_icons_flutter:
  path_drawing:
  quick_actions:
  package_info_plus:
  url_launcher:
  cached_network_image:
  path:
  easy_localization:
  xml:
  flutter_localized_locales: ^1.1.2
  uuid:
  recase:
  in_app_update:
  flutter_downloader:
  dio:
  image:
  blurhash_dart:
  flutter_blurhash:
  mobx:
  flutter_mobx:
  mobx_codegen:
  waterfall_flow:
  worker_manager:
  crayola:
  blake2:
  file_selector:
  file_selector_macos:
  file_selector_linux:
  file_selector_windows:

  rich_text_editor:
    git: https://github.com/namhyun-gu/flutter_rich_text_editor
  loggy:
    git: https://github.com/HrX03/loggy

dev_dependencies:
  moor_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  mockito:

dependency_overrides:
  intl: '0.17.0-nullsafety.2'
  platform: '2.2.1'
  path: '1.7.0'
  flutter_localized_locales: '1.1.2'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Light.otf
          weight: 300
        - asset: fonts/Manrope-Regular.otf
          weight: 400
        - asset: fonts/Manrope-Medium.otf
          weight: 500
        - asset: fonts/Manrope-SemiBold.otf
          weight: 600
        - asset: fonts/Manrope-Bold.otf
          weight: 700
    - family:  ValeraRound
      fonts:
        - asset: fonts/ValeraRound.ttf