name: potato_notes
description: Official POSP notes app
publish_to: 'none'
version: 2.0.0-beta1+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqlite3_flutter_libs:
  moor:
  json_serializable:
  sqflite:
  path_provider:
  image_picker:
  back_button_interceptor:
  shared_preferences:
  local_auth:
  flutter_secure_storage:
  http: 
  jwt_decode:
  intl:
  flutter_local_notifications:
  share_plus:
  animations:
  material_design_icons_flutter:
  path_drawing:
  quick_actions:
  package_info_plus:
  url_launcher:
  cached_network_image:
  path:
  easy_localization:
  xml:
  uuid:
  recase:
  in_app_update:
  flutter_downloader:
  dio:
  image:
  blurhash_dart:
  flutter_blurhash:
  mobx:
  flutter_mobx:
  mobx_codegen:
  waterfall_flow:
  worker_manager:
  crayola:
  blake2:
  file_selector:
  file_selector_macos:
  file_selector_linux:
  file_selector_windows:
  image_size_getter:
  sqflite_common_ffi:
  file_picker:

  loggy:
    git: https://github.com/HrX03/loggy

dev_dependencies:
  moor_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  mockito:

dependency_overrides:
  intl: '0.17.0'
  platform: '3.0.0'
  path: '1.8.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: ValeraRound
      fonts:
        - asset: fonts/ValeraRound.ttf