name: potato_notes
description: Official POSP notes app
publish_to: 'none'
version: 2.0.0-beta1+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.0

  back_button_interceptor: ^5.0.0-nullsafety.1
  blurhash_dart: ^1.0.0-nullsafety.0

  collection: ^1.15.0

  dio: ^4.0.0-beta4

  easy_localization:
    git: https://github.com/HrX03/easy_localization

  file_picker: ^3.0.0-nullsafety.2
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.5.2-nullsafety.0
  flutter_local_notifications: ^5.0.0-nullsafety.0
  flutter_mobx: ^2.0.0-nullsafety.1
  flutter_secure_storage: ^4.0.0

  http: ^0.13.0

  image: ^3.0.1
  image_picker: ^0.7.2
  image_picker_for_web: ^2.0.0
  image_size_getter:
    git:
      url: https://github.com/HrX03/dart_image_size_getter
      path: library/
  in_app_update:
  intl: ^0.17.0

  local_auth: ^1.1.0
  loggy:
    git: https://github.com/HrX03/loggy

  material_design_icons_flutter: ^5.0.5955-rc.1
  mobx: ^2.0.0-nullsafety.3
  moor: ^4.1.0

  package_info_plus: ^1.0.0
  path: ^1.8.0
  path_drawing: ^0.5.0-nullsafety.0
  path_provider: ^2.0.0

  quick_actions: ^0.5.0

  recase: ^4.0.0-nullsafety.0

  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share_plus: ^2.0.0
  shared_preferences: ^2.0.4
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  sqlite3_flutter_libs: ^0.4.0+1

  universal_platform: ^1.0.0-nullsafety
  url_launcher: ^6.0.2
  uuid: ^3.0.1

  waterfall_flow: ^3.0.1

  xml: ^5.0.2

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.2
  lint:
  mobx_codegen:
    git:
      url: https://github.com/mobxjs/mobx.dart
      path: mobx_codegen
      ref: null_safety
  mockito: ^5.0.0-nullsafety.7
  moor_generator: ^4.1.0

dependency_overrides:
  analyzer: ^1.1.0
  pub_semver: ^1.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: ValeraRound
      fonts:
        - asset: fonts/ValeraRound.ttf