name: potato_notes
description: Official POSP notes app
publish_to: "none"
version: 2.0.1+21

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animated_vector:
    git: https://github.com/PotatoProject/animated_vector
  animations: ^2.0.0
  archive: ^3.1.2

  back_button_interceptor: ^5.0.1
  biometric_storage: ^2.0.3
  bitsdojo_window: ^0.1.1+1
  blurhash_dart: ^1.0.2

  collection: ^1.15.0
  cryptography: ^2.0.1

  dio: ^4.0.0

  easy_localization:
    git: https://github.com/HrX03/easy_localization

  file_picker: ^3.0.3
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.6.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_local_notifications: ^6.0.0
  flutter_mobx: ^2.0.0

  http: ^0.13.3

  image: ^3.0.2
  image_picker: ^0.8.1+3
  image_picker_for_web: ^2.0.0
  image_size_getter: ^1.0.0
  in_app_update: ^2.0.0
  intl: ^0.17.0

  local_auth: ^1.1.6
  loggy:
    git: https://github.com/HrX03/loggy

  material_design_icons_flutter: ^5.0.5955-rc.1
  mobx: ^2.0.1
  monet: ^0.1.0
  moor: ^4.4.0

  package_info_plus: ^1.0.3
  path: ^1.8.0
  path_drawing: ^0.5.1
  path_provider: ^2.0.2

  quick_actions: ^0.6.0

  recase: ^4.0.0

  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs
  
  toml: ^0.11.0

  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.8
  uuid: ^3.0.4

  waterfall_flow: ^3.0.1
  webcrypto:
    git: https://github.com/gargakshit/webcrypto.dart

  xml: ^5.1.2

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mobx_codegen: ^2.0.1
  mockito: ^5.0.10
  moor_generator: ^4.4.0

flutter:
  uses-material-design: true
  assets:
    - config.json
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: ValeraRound
      fonts:
        - asset: fonts/ValeraRound.ttf
