name: potato_notes
description: Official POSP notes app
publish_to: 'none'
version: 2.0.0-beta1+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations:

  back_button_interceptor:
  blake2:
  blurhash_dart:

  crayola:

  dio:

  easy_localization:

  file_picker:
  file_selector:
  file_selector_macos:
  file_selector_linux:
  file_selector_windows:
  flutter_blurhash:
  flutter_downloader:
  flutter_local_notifications:
  flutter_mobx:
  flutter_secure_storage:

  http:

  image:
  image_picker:
  image_size_getter:
  in_app_update:
  intl:

  json_serializable:
  jwt_decode:

  local_auth:
  loggy:
    git: https://github.com/HrX03/loggy

  material_design_icons_flutter:
  mobx:
  moor: ^4.1.0

  package_info_plus:
  path:
  path_drawing: ^0.5.0-nullsafety.0
  path_provider: ^2.0.0

  quick_actions:

  recase:

  share_plus:
  shared_preferences:
  sqflite:
  sqflite_common_ffi:
  sqlite3_flutter_libs:

  url_launcher:
  uuid:

  waterfall_flow:
  worker_manager:

  xml:

dev_dependencies:
  moor_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  mockito:
  mobx_codegen:

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: ValeraRound
      fonts:
        - asset: fonts/ValeraRound.ttf