[info]
name = "Monet light"
author = "HrX03"
version = 1
brightness = "light"
useMaterial3 = true

[shapes.smallComponents]
type = "rounded"
radius.all = 4

[shapes.mediumComponents]
type = "rounded"
radius.all = 4

[shapes.largeComponents]
type = "rounded"
radius.all = 16

[shapes.fabOverride]
type = "rounded"
radius.all = 16

[shapes.bottomSheetOverride]
type = "rounded"

[shapes.dialogOverride]
type = "rounded"
radius.all = 8

[shapes.chipOverride]
type = "stadium"

[shapes.menuOverride]
type = "rounded"
radius.all = 16

[shapes.cardOverride]
type = "rounded"
radius.all = 16

[colors]
primary = "monet.primaries.600"
primaryContainer = "monet.primaries.100"
secondary = "monet.secondaries.600"
secondaryContainer = "monet.secondaries.100"
tertiary = "monet.tertiaries.600"
tertiaryContainer = "monet.tertiaries.100"
error = "monet.errors.600"
errorContainer = "monet.errors.100"

background = "monet.neutrals.10"
surface = "monet.neutrals.50"
surfaceVariant = "monet.neutralVariants.100"

onPrimary = "monet.primaries.0"
onSecondary = "monet.secondaries.0"
onTertiary = "monet.tertiaries.0"
onPrimaryContainer = "monet.primaries.900"
onSecondaryContainer = "monet.secondaries.900"
onTertiaryContainer = "monet.tertiaries.900"
onError = "monet.errors.0"
onErrorContainer = "monet.errors.900"

onBackground = "monet.neutrals.900"
onSurface = "monet.neutrals.900"
onSurfaceVariant = "monet.neutralVariants.700"

outline = "monet.neutralVariants.500"
shadow = "monet.neutrals.1000"

inverseSurface = "monet.neutrals.800"
onInverseSurface = "monet.neutrals.50"
inversePrimary = "monet.primaries.200"

[colors.illustrations]
base = "monet.secondaries.600"
contrast = "monet.secondaries.800"
invertedContrast = "monet.secondaries.300"