[info]
name = "Monet dark"
author = "HrX03"
version = 1
brightness = "dark"

[shapes.smallComponents]
type = "rounded"
radius.all = 4

[shapes.mediumComponents]
type = "rounded"
radius.all = 4

[shapes.largeComponents]
type = "rounded"
radius.all = 16

[shapes.fabOverride]
type = "rounded"
radius.all = 16

[shapes.bottomSheetOverride]
type = "rounded"

[shapes.dialogOverride]
type = "rounded"
radius.all = 8

[shapes.chipOverride]
type = "stadium"

[shapes.menuOverride]
type = "rounded"
radius.all = 16

[shapes.cardOverride]
type = "rounded"
radius.all = 16

[colors]
primary = "monet.accent1.300"
surface = "monet.accent2.800"
background = "monet.accent2.900"
error = "color.red.400"
onPrimary = "monet.accent2.800"
onSurface = "monet.accent2.50"
onBackground = "monet.accent2.50"
onError = "color.grey.900"

[colors.illustrations]
base = "monet.accent2.400"
contrast = "monet.accent2.200"
invertedContrast = "monet.accent2.600"